const $=s=>document.querySelector(s);const client=window.salvatoreSupabase;let availability={status:'available',wait:'25–35 min',note:''};
function render(){const labels={available:'Pedidos disponibles',busy:'Alta demanda',closed:'Cupos agotados'};const banner=$('#previewBanner');banner.className=`preview-banner ${availability.status}`;$('#previewIcon').textContent=availability.status==='available'?'●':availability.status==='busy'?'◐':'×';$('#previewTitle').textContent=labels[availability.status];$('#previewDetail').textContent=availability.status==='closed'?(availability.note||'No estamos recibiendo pedidos por ahora'):`Tiempo estimado: ${availability.wait}${availability.note?` · ${availability.note}`:''}`}
function loadForm(){const form=$('#availabilityForm');form.availability.value=availability.status;form.wait.value=availability.wait;form.availabilityNote.value=availability.note}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function showError(message){const el=$('#loginError');el.textContent=message;el.classList.remove('hidden')}
async function loadAvailability(){const {data,error}=await client.from('store_availability').select('status,wait,note').eq('id',1).single();if(error)throw error;availability=data;loadForm();render()}
async function verifyAdmin(){const {data:{user}}=await client.auth.getUser();if(!user)return false;const {data,error}=await client.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function showAdmin(){if(!await verifyAdmin()){await client.auth.signOut();showError('Este usuario no tiene permisos de administración.');return}$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');try{await loadAvailability()}catch(error){toast('Aún falta ejecutar la configuración de base de datos.')}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;button.textContent='Ingresando...';$('#loginError').classList.add('hidden');const data=new FormData(event.currentTarget);const {error}=await client.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});button.disabled=false;button.textContent='Ingresar';if(error)return showError('Correo o contraseña incorrectos.');await showAdmin()});
$('#availabilityForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;button.textContent='Guardando...';const data=new FormData(event.currentTarget);const next={status:data.get('availability'),wait:data.get('wait'),note:data.get('availabilityNote').trim(),updated_at:new Date().toISOString()};const {error}=await client.from('store_availability').update(next).eq('id',1);button.disabled=false;button.textContent='Guardar cambios';if(error)return toast('No fue posible guardar el cambio.');availability=next;render();toast('Disponibilidad actualizada para los clientes.');});
$('#logoutButton').addEventListener('click',async()=>{await client.auth.signOut();$('#adminView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginForm').reset()});
if(!client){showError('Falta la configuración de Supabase.')}else{client.auth.getSession().then(({data:{session}})=>{if(session)showAdmin()})}
