const $=s=>document.querySelector(s);const client=window.salvatoreSupabase;const defaults={status:'available',wait:'25–35 min',note:''};let worlds={pizza:{...defaults},waffle:{...defaults}};
function selectedWorld(){return $('#availabilityForm').world.value}function activeAvailability(){return worlds[selectedWorld()==='waffle'?'waffle':'pizza']}
function render(){const availability=activeAvailability(),labels={available:'Pedidos disponibles',busy:'Alta demanda',closed:'Cupos agotados'},banner=$('#previewBanner');banner.className=`preview-banner ${availability.status}`;$('#previewIcon').textContent=availability.status==='available'?'●':availability.status==='busy'?'◐':'×';$('#previewTitle').textContent=labels[availability.status];$('#previewDetail').textContent=availability.status==='closed'?(availability.note||'No estamos recibiendo pedidos por ahora'):`Tiempo estimado: ${availability.wait}${availability.note?` · ${availability.note}`:''}`}
function loadForm(){const form=$('#availabilityForm'),availability=activeAvailability();form.availability.value=availability.status;form.wait.value=availability.wait;form.availabilityNote.value=availability.note}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}function showError(message){const el=$('#loginError');el.textContent=message;el.classList.remove('hidden')}
function record(data,world){return {status:data[`${world}_status`]||data.status||defaults.status,wait:data[`${world}_wait`]||data.wait||defaults.wait,note:data[`${world}_note`]??data.note??defaults.note}}
async function loadAvailability(){const {data,error}=await client.from('store_availability').select('pizza_status,pizza_wait,pizza_note,waffle_status,waffle_wait,waffle_note').eq('id',1).single();if(error)throw error;worlds={pizza:record(data,'pizza'),waffle:record(data,'waffle')};loadForm();render()}
async function verifyAdmin(){const {data:{user}}=await client.auth.getUser();if(!user)return false;const {data,error}=await client.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function showAdmin(){if(!await verifyAdmin()){await client.auth.signOut();showError('Este usuario no tiene permisos de administración.');return}$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');try{await loadAvailability()}catch(error){toast('Falta ejecutar la migración de disponibilidad por mundo en Supabase.')}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;button.textContent='Ingresando...';$('#loginError').classList.add('hidden');const data=new FormData(event.currentTarget);const {error}=await client.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});button.disabled=false;button.textContent='Ingresar';if(error)return showError('Correo o contraseña incorrectos.');await showAdmin()});
$('#availabilityForm').world.addEventListener('change',()=>{loadForm();render()});
$('#availabilityForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),data=new FormData(event.currentTarget),target=data.get('world'),next={status:data.get('availability'),wait:data.get('wait'),note:data.get('availabilityNote').trim()},update={updated_at:new Date().toISOString()};for(const world of target==='both'?['pizza','waffle']:[target]){worlds[world]=next;update[`${world}_status`]=next.status;update[`${world}_wait`]=next.wait;update[`${world}_note`]=next.note}button.disabled=true;button.textContent='Guardando...';const {error}=await client.from('store_availability').update(update).eq('id',1);button.disabled=false;button.textContent='Guardar cambios';if(error)return toast('No fue posible guardar el cambio.');render();toast(target==='both'?'Estado actualizado para Pizzas y Waffles.':`Estado actualizado para ${target==='pizza'?'Pizzas':'Waffles'}.`)});
$('#logoutButton').addEventListener('click',async()=>{await client.auth.signOut();$('#adminView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginForm').reset()});if(!client){showError('Falta la configuración de Supabase.')}else{client.auth.getSession().then(({data:{session}})=>{if(session)showAdmin()})}
