const money = value => new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value);
const products = [
  ['margarita','Margarita',6500,'Pomodoro · mozzarella · albahaca fresca · Aceite de Oliva','🍕','pizza'],['jamon','Jamón & Champiñón',7000,'Pomodoro · mozzarella · jamón pierna · champiñón laminado','🍕','pizza'],['napolitana','Napolitana',7500,'Pomodoro · mozzarella · jamón · tomate · aceitunas negras · orégano','🍕','pizza'],['pepperoni','Pepperoni',7500,'Pomodoro · mozzarella · pepperoni americano crujiente','🍕','pizza'],['capricciosa','Capricciosa',8000,'Pomodoro · mozzarella · jamón · champiñón · aceitunas · alcachofa','🍕','pizza'],['longaniza','Longaniza',7500,'Pomodoro · mozzarella · longaniza artesanal · cebolla','🍕','pizza'],['pesto','Pesto',7500,'Pomodoro · mozzarella · salsa pesto · champiñón · Aceite de Oliva','🍕','pizza'],['bbq','BBQ',7500,'Salsa BBQ ahumada · mozzarella · tocino crocante · cebolla','🍕','pizza'],
  ['waffle','Waffle Salvatore Estrella',1000,'Pancito waffle relleno de manjar artesanal y salsa de chocolate semiamargo.','🧇','waffle'],
  ['pepsi','Pepsi',1000,'Lata 350 ml','🥤','drink'],['bilz','Bilz',1000,'Lata 350 ml','🥤','drink'],['pap','Pap',1000,'Lata 350 ml','🥤','drink'],['kem','Kem Xtreme',1000,'Lata 350 ml','🥤','drink'],['seven','7Up',1000,'Lata 350 ml','🥤','drink'],['zero','Pepsi Zero',1000,'Lata 350 ml','🥤','drink']
].map(([id,name,price,description,icon,type])=>({id,name,price,description,icon,type}));
const pizzaExtras=['Extra Mozzarella','Extra Pepperoni','Champiñones','Tocino','Aceitunas Negras','Cebolla','Tomate fresco','Albahaca']; const waffleExtras=['Extra salsa de chocolate','Chispas de chocolate','Extra manjar'];
let cart=JSON.parse(localStorage.getItem('salvatore-cart')||'[]'), selected=null, quantity=1;
let availabilityByWorld=JSON.parse(localStorage.getItem('salvatore-availability-worlds')||'{"pizza":{"status":"available","wait":"25–35 min","note":""},"waffle":{"status":"available","wait":"25–35 min","note":""}}'),activeWorld='pizza',availability=availabilityByWorld.pizza;
const $=s=>document.querySelector(s); const byId=id=>products.find(p=>p.id===id);
function card(p){return `<article class="card ${p.type}-card"><div class="card-visual">${p.icon}</div><div class="card-body"><h3>${p.name}</h3><p>${p.description}</p><div class="card-footer"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${p.id}">Agregar</button></div></div></article>`}
$('#pizzaGrid').innerHTML=products.filter(p=>p.type==='pizza').map(card).join('');
$('#waffleGrid').innerHTML=card(products.find(p=>p.id==='waffle'))+`<article class="card upcoming"><div class="card-visual">✨</div><div class="card-body"><h3>Próximamente</h3><p>Más sabores dulces para acompañar tus tardes.</p></div></article>`;
$('#drinkGrid').innerHTML=products.filter(p=>p.type==='drink').map(card).join('');
function persist(){localStorage.setItem('salvatore-cart',JSON.stringify(cart));renderCart()}
function renderAvailability(){const labels={available:'Pedidos disponibles',busy:'Alta demanda',closed:'Cupos agotados'};const banner=$('#availabilityBanner');banner.className=`availability-banner ${availability.status}`;$('#availabilityIcon').textContent=availability.status==='available'?'●':availability.status==='busy'?'◐':'×';$('#availabilityTitle').textContent=labels[availability.status];$('#availabilityDetail').textContent=availability.status==='closed'?(availability.note||'No estamos recibiendo pedidos por ahora'):`Tiempo estimado: ${availability.wait}${availability.note?` · ${availability.note}`:''}`}
async function loadRemoteAvailability(){if(!window.salvatoreSupabase)return;const {data,error}=await window.salvatoreSupabase.from('store_availability').select('status,wait,note').eq('id',1).single();if(!error&&data){availability=data;renderAvailability()}}
function total(){return cart.reduce((sum,item)=>sum+item.unit*item.qty,0)}
function renderCart(){const itemWrap=$('#cartItems'), empty=$('#cartEmpty'); $('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);$('#cartSubtotal').textContent=money(total()); empty.classList.toggle('hidden',cart.length>0);itemWrap.innerHTML=cart.map((x,i)=>`<div class="cart-item"><span class="cart-item-icon">${x.icon}</span><div class="cart-item-info"><b>${x.name}</b><small>${x.extras.length?x.extras.join(', '):''}${x.note?` · ${x.note}`:''}</small><strong>${money(x.unit*x.qty)}</strong></div><div class="cart-item-actions"><button data-minus="${i}">−</button><span>${x.qty}</span><button data-plus="${i}">+</button><button data-remove="${i}" aria-label="Eliminar">×</button></div></div>`).join('')}
function openProduct(id){selected=byId(id);quantity=1;const extras=selected.type==='pizza'?pizzaExtras:selected.type==='waffle'?waffleExtras:[];const notePlaceholder=selected.type==='waffle'?'Ej. sin salsa de chocolate, con extra manjar...':'Ej. sin cebolla, bien dorada...';const noteField=selected.type==='drink'?'':`<label class="modal-note">Instrucciones especiales<textarea id="productNote" placeholder="${notePlaceholder}"></textarea></label>`; $('#modalContent').innerHTML=`<button class="close product-close" data-close="productModal" aria-label="Cerrar producto">×</button><div class="card-visual">${selected.icon}</div><h2 id="modalTitle">${selected.name}</h2><p class="price">${money(selected.price)}</p><p class="description">${selected.description}</p>${extras.length?`<fieldset><legend>Hazlo a tu gusto <small>(+$500 c/u)</small></legend><div class="extras">${extras.map(x=>`<label><input type="checkbox" value="${x}" /> ${x}</label>`).join('')}</div></fieldset>`:''}${noteField}<div class="quantity-row"><b>Cantidad</b><div class="quantity"><button id="decrease" type="button">−</button><output id="quantity">1</output><button id="increase" type="button">+</button></div></div><button id="confirmAdd" class="primary-button full">Agregar · <span id="modalTotal">${money(selected.price)}</span></button>`;$('#productModal').classList.remove('hidden')}
function modalTotal(){const n=$$('#modalContent input[type=checkbox]:checked').length;$('#quantity').textContent=quantity;$('#modalTotal').textContent=money((selected.price+n*500)*quantity)}
function addSelected(){const extras=$$('#modalContent input[type=checkbox]:checked').map(x=>x.value);cart.push({name:selected.name,icon:selected.icon,unit:selected.price+extras.length*500,extras,note:$('#productNote')?.value.trim()||'',qty:quantity});persist();closeModal('productModal');openCart();toast('¡Agregado a tu pedido!')}
function $$(s){return [...document.querySelectorAll(s)]}function closeModal(id){$('#'+id).classList.add('hidden')}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerShade').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerShade').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)openProduct(add.dataset.add);if(e.target.closest('[data-close]'))closeModal(e.target.closest('[data-close]').dataset.close);if(e.target.id==='increase'){quantity++;modalTotal()}if(e.target.id==='decrease'&&quantity>1){quantity--;modalTotal()}if(e.target.id==='confirmAdd')addSelected();if(e.target.matches('[data-plus]')){cart[e.target.dataset.plus].qty++;persist()}if(e.target.matches('[data-minus]')){let i=e.target.dataset.minus;if(cart[i].qty>1)cart[i].qty--;persist()}if(e.target.matches('[data-remove]')){cart.splice(e.target.dataset.remove,1);persist()}if(e.target.closest('#cartButton'))openCart();if(e.target.closest('#closeCart')||e.target.id==='drawerShade')closeCart();if(e.target.closest('#checkoutButton')){if(!cart.length){toast('Agrega algo rico antes de continuar.');return}if(availability.status==='closed'){toast('Por ahora los cupos están agotados.');return}closeCart();$('#checkoutModal').classList.remove('hidden');updateCheckoutTotal()}if(e.target.closest('#copyBank')){navigator.clipboard.writeText('Banco Estado\nCuenta RUT: 20322788\nRUT: 20.322.788-4\nCarlos Borquez Vidal\ncarlosmbv2000@gmail.com');toast('Datos bancarios copiados.')};if(e.target.closest('.portal')){start(e.target.closest('.portal').dataset.start)}if(e.target.id==='skipWelcome')start();if(e.target.closest('#statusAdmin')){const form=$('#availabilityForm');form.availability.value=availability.status;form.wait.value=availability.wait;form.availabilityNote.value=availability.note;$('#availabilityModal').classList.remove('hidden')}});
document.addEventListener('change',e=>{if(e.target.closest('#modalContent'))modalTotal();if(e.target.name==='delivery'){const delivery=e.target.value;$('#addressWrap').classList.toggle('hidden',delivery==='pickup');$('#addressWrap input').required=delivery!=='pickup';updateCheckoutTotal()}if(e.target.name==='payment'){$('#bankInfo').classList.toggle('hidden',e.target.value!=='transfer')}});
function deliveryCost(){return {pickup:0,urban:500,lomas:1000}[document.querySelector('input[name=delivery]:checked')?.value||'pickup']}function updateCheckoutTotal(){$('#checkoutTotal').textContent=money(total()+deliveryCost())}
$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target), method=d.get('payment')==='cash'?'Efectivo':'Transferencia bancaria';const delivery={pickup:'Retiro en Campillo 920',urban:'Delivery radio urbano Mulchén',lomas:'Delivery Lomas Verdes y alrededores'}[d.get('delivery')];const lines=cart.map(x=>`• ${x.qty}x ${x.name}${x.extras.length?` (+ ${x.extras.join(', ')})`:''} — ${money(x.unit*x.qty)}`).join('\n');const message=`¡Hola Salvatore! Quiero hacer este pedido:%0A%0A${encodeURIComponent(lines)}%0A%0A*Cliente:* ${encodeURIComponent(d.get('name'))}%0A*Teléfono:* ${encodeURIComponent(d.get('phone'))}%0A*Entrega:* ${encodeURIComponent(delivery)}${d.get('address')?`%0A*Dirección:* ${encodeURIComponent(d.get('address'))}`:''}%0A*Tiempo estimado:* ${encodeURIComponent(availability.wait)}%0A*Pago:* ${encodeURIComponent(method)}${d.get('notes')?`%0A*Notas:* ${encodeURIComponent(d.get('notes'))}`:''}%0A%0A*Subtotal:* ${encodeURIComponent(money(total()))}%0A*Total:* ${encodeURIComponent(money(total()+deliveryCost()))}`;window.open(`https://wa.me/56950602621?text=${message}`,'_blank');});
$('#availabilityForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);availability={status:d.get('availability'),wait:d.get('wait'),note:d.get('availabilityNote').trim()};localStorage.setItem('salvatore-availability',JSON.stringify(availability));renderAvailability();closeModal('availabilityModal');toast('Estado de disponibilidad actualizado.');});
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setWorld(world){const pizza=world==='pizza',all=world==='all';document.body.classList.remove('pizza-world','waffle-world','all-world');document.body.classList.add(`${world}-world`);$('#headerLogo').src=world==='waffle'?'assets/salvatore-waffle-logo.jpg':'assets/salvatore-pizza-logo.png';$('#headerLogo').alt=world==='waffle'?'Logo Salvatore Waffle':'Logo Salvatore Pizza';$('#headerBrand').textContent=all?'Salvatore':pizza?'Salvatore Pizza':'Salvatore Waffle';$('#headerSubtitle').textContent=all?'Pizzas, Waffles & Bebidas':pizza?'Artesanales & Calidad':'Calientitos & Suaves';$('#heroEyebrow').textContent=all?'Pizzas artesanales · Waffles · Bebidas · Mulchén':pizza?'Pizzas artesanales · Mulchén':'Waffles horneados al momento · Mulchén';$('#heroTitle').innerHTML=all?'Todo lo bueno<br /><em>en un solo pedido.</em>':pizza?'El sabor que<br /><em>te hace volver.</em>':'Un momento dulce<br /><em>para sonreír.</em>';$('#heroDescription').textContent=all?'Revisa nuestras pizzas, waffles y bebidas disponibles para combinar a tu gusto.':pizza?'Masa hecha a mano, ingredientes frescos y mucho sabor en cada porción.':'Waffles suaves, recién horneados, rellenos de manjar y bañados en chocolate.';$('#heroButton').href='#pizzas';$('#heroButton').firstChild.textContent=all?'Ver menú completo ':'Ver el menú ';$('#heroFood').textContent=world==='waffle'?'🧇':'🍕';$('#heroPrice').innerHTML=world==='waffle'?'desde<br /><b>$1.000</b>':'desde<br /><b>$6.500</b>';}
function start(section){const world=section==='waffles'?'waffle':section==='all'?'all':'pizza';setWorld(world);$('#welcome').classList.add('out');window.scrollTo({top:0,behavior:'smooth'})}
$('#changeWorld').addEventListener('click',()=>{$('#welcome').classList.remove('out');window.scrollTo({top:0,behavior:'smooth'})});
document.addEventListener('click',e=>{if(e.target.id==='skipWelcome'){e.stopImmediatePropagation();start('all')}},true);
const setWorldBase=setWorld;
setWorld=world=>{activeWorld=world==='waffle'?'waffle':'pizza';availability=availabilityByWorld[activeWorld]||availabilityByWorld.pizza;setWorldBase(world);renderAvailability()};
loadRemoteAvailability=async()=>{if(!window.salvatoreSupabase)return;const {data,error}=await window.salvatoreSupabase.from('store_availability').select('pizza_status,pizza_wait,pizza_note,waffle_status,waffle_wait,waffle_note').eq('id',1).single();if(!error&&data){availabilityByWorld={pizza:{status:data.pizza_status||'available',wait:data.pizza_wait||'25–35 min',note:data.pizza_note||''},waffle:{status:data.waffle_status||'available',wait:data.waffle_wait||'25–35 min',note:data.waffle_note||''}};localStorage.setItem('salvatore-availability-worlds',JSON.stringify(availabilityByWorld));availability=availabilityByWorld[activeWorld]||availabilityByWorld.pizza;renderAvailability()}};
renderCart();renderAvailability();loadRemoteAvailability();setInterval(loadRemoteAvailability,60000);
