const $=s=>document.querySelector(s),client=window.salvatoreSupabase;let items=[],showMissingOnly=false;
const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));const number=value=>Math.max(0,Number(value)||0);const display=value=>new Intl.NumberFormat('es-CL',{maximumFractionDigits:2}).format(value);const units=['unidades','kg','g','litros','ml','paquetes'];const unitSelect=value=>{const options=units.includes(value)?units:[value,...units];return `<select data-field="unit">${options.map(unit=>`<option value="${esc(unit)}" ${unit===value?'selected':''}>${esc(unit)}</option>`).join('')}</select>`};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}function showError(message){const el=$('#loginError');el.textContent=message;el.classList.remove('hidden')}function databaseMessage(error,action){if(error.code==='23505')return 'Ese ingrediente ya existe en este mundo.';if(error.code==='42501')return 'Tu cuenta no tiene permiso para modificar la planificación.';if(error.code==='42P01')return 'Falta ejecutar la migración de planificación en Supabase.';if(error.code==='23514')return 'Revisa que los valores ingresados sean válidos.';return `${action}: ${error.message||'error desconocido'}`}
function buy(item){return Math.max(0,number(item.target)-number(item.stock))}function renderWorld(world){const target=$(`#${world}List`),worldItems=items.filter(item=>item.world===world);target.querySelector('.inventory-table,.empty-inventory')?.remove();if(!worldItems.length){target.insertAdjacentHTML('beforeend','<p class="empty-inventory">Aún no hay ingredientes en esta lista.</p>');return}target.insertAdjacentHTML('beforeend',`<table class="inventory-table"><thead><tr><th>Ingrediente</th><th>Meta para producir</th><th>En stock</th><th>Unidad</th><th>Comprar</th><th></th></tr></thead><tbody>${worldItems.map(item=>{const missing=buy(item);return `<tr data-id="${item.id}" class="${missing?'needs-stock':'is-ready'}"><td class="item-name">${esc(item.name)}</td><td data-label="Meta para producir"><input data-field="target" type="number" min="0" step="0.01" value="${item.target}" /></td><td data-label="En stock"><input data-field="stock" type="number" min="0" step="0.01" value="${item.stock}" /></td><td data-label="Unidad">${unitSelect(item.unit)}</td><td data-label="Comprar" class="buy-amount ${missing?'':'ok'}">${missing?`${display(missing)} ${esc(item.unit)}`:'Listo'}</td><td><button class="remove-item" data-remove="${item.id}" type="button">Quitar</button></td></tr>`}).join('')}</tbody></table>`)}
function applyInventoryFilter(){document.querySelectorAll('tr.is-ready').forEach(row=>row.hidden=showMissingOnly);document.querySelectorAll('.filter-button').forEach(button=>button.classList.toggle('active',button.dataset.filter===(showMissingOnly?'missing':'all')))}function render(){const missing=items.filter(item=>buy(item)>0).length;renderWorld('pizza');renderWorld('waffle');$('#pendingCount').textContent=missing;$('#missingFilterCount').textContent=missing;applyInventoryFilter()}
async function loadItems(){const {data,error}=await client.from('production_inventory_items').select('id,world,name,unit,target,stock,position').order('world').order('position').order('name');if(error)throw error;items=data||[];render()}
async function verifyAdmin(){const {data:{user}}=await client.auth.getUser();if(!user)return false;const {data,error}=await client.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function showPlanner(){if(!await verifyAdmin()){await client.auth.signOut();showError('Este usuario no tiene permisos de administración.');return}$('#loginView').classList.add('hidden');$('#plannerView').classList.remove('hidden');try{await loadItems()}catch(error){toast('Falta ejecutar la migración de planificación en Supabase.')}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),data=new FormData(event.currentTarget);button.disabled=true;button.textContent='Ingresando...';const {error}=await client.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});button.disabled=false;button.textContent='Ingresar';if(error)return showError('Correo o contraseña incorrectos.');await showPlanner()});
document.addEventListener('input',event=>{const input=event.target.closest('[data-field]');if(!input)return;const row=input.closest('tr'),item=items.find(value=>String(value.id)===row.dataset.id);if(!item)return;item[input.dataset.field]=input.dataset.field==='unit'?input.value:number(input.value);const missing=buy(item),output=row.querySelector('.buy-amount'),pending=items.filter(value=>buy(value)>0).length;row.className=missing?'needs-stock':'is-ready';output.className=`buy-amount ${missing?'':'ok'}`;output.textContent=missing?`${display(missing)} ${item.unit}`:'Listo';$('#pendingCount').textContent=pending;$('#missingFilterCount').textContent=pending;applyInventoryFilter()});
document.addEventListener('change',event=>{const input=event.target.closest('select[data-field="unit"]');if(!input)return;const row=input.closest('tr'),item=items.find(value=>String(value.id)===row.dataset.id);if(!item)return;item.unit=input.value;const missing=buy(item),output=row.querySelector('.buy-amount');output.className=`buy-amount ${missing?'':'ok'}`;output.textContent=missing?`${display(missing)} ${item.unit}`:'Listo'});
document.addEventListener('click',event=>{const filter=event.target.closest('[data-filter]');if(!filter)return;showMissingOnly=filter.dataset.filter==='missing';applyInventoryFilter()});
$('#saveInventory').addEventListener('click',async()=>{const button=$('#saveInventory');button.disabled=true;button.textContent='Guardando...';const updates=items.map(item=>client.from('production_inventory_items').update({target:number(item.target),stock:number(item.stock),unit:item.unit.trim()||'unidades',updated_at:new Date().toISOString()}).eq('id',item.id));const results=await Promise.all(updates);button.disabled=false;button.textContent='Guardar planificación';if(results.some(result=>result.error))return toast('No se pudieron guardar todos los cambios.');await loadItems();toast('Planificación guardada.')});
$('#saveInventoryBottom').addEventListener('click',()=>$('#saveInventory').click());
$('#addItemForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),name=data.get('name').trim(),button=form.querySelector('button');button.disabled=true;button.textContent='Agregando...';const {error}=await client.from('production_inventory_items').insert({world:data.get('world'),name,unit:data.get('unit'),target:number(data.get('target')),stock:number(data.get('stock')),position:items.filter(item=>item.world===data.get('world')).length+1});button.disabled=false;button.textContent='Agregar a la lista';if(error)return toast(databaseMessage(error,'No se pudo agregar el ingrediente'));form.reset();await loadItems();toast('Ingrediente agregado.')});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-remove]');if(!button)return;const item=items.find(value=>String(value.id)===button.dataset.remove);if(!item||!confirm(`¿Quitar ${item.name} de la lista?`))return;const {error}=await client.from('production_inventory_items').delete().eq('id',item.id);if(error)return toast('No se pudo quitar el ingrediente.');items=items.filter(value=>value.id!==item.id);render();toast('Ingrediente quitado.')});
$('#logoutButton').addEventListener('click',async()=>{await client.auth.signOut();$('#plannerView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginForm').reset()});if(!client){showError('Falta la configuración de Supabase.')}else{client.auth.getSession().then(({data:{session}})=>{if(session)showPlanner()})}
