-- ==========================================================================
-- SALVATORE PIZZAS & WAFFLES — MIGRACIÓN DE PEDIDOS (PERMISOS COMPLETOS)
-- Ejecuta todo este archivo en Supabase: SQL Editor > New query > Run.
-- ==========================================================================

-- 1. Crear tablas si no existen
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_phone text not null,
  delivery_type text not null check (delivery_type in ('pickup', 'delivery', 'urban', 'lomas')),
  delivery_address text default '',
  payment_method text not null check (payment_method in ('cash', 'transfer')),
  notes text default '',
  subtotal numeric not null check (subtotal >= 0),
  delivery_cost numeric not null check (delivery_cost >= 0),
  total numeric not null check (total >= 0),
  status text not null check (status in ('pending', 'preparing', 'ready', 'delivered', 'cancelled')) default 'pending',
  world text not null check (world in ('pizza', 'waffle', 'all')) default 'pizza',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0),
  total_price numeric not null check (total_price >= 0),
  extras text[] default '{}',
  notes text default '',
  created_at timestamptz not null default now()
);

-- 2. Habilitar Seguridad por Fila (RLS) y actualizar constraints si ya existía
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.orders drop constraint if exists orders_delivery_type_check;
alter table public.orders add constraint orders_delivery_type_check check (delivery_type in ('pickup', 'delivery', 'urban', 'lomas'));

-- 3. Limpiar políticas previas para evitar duplicados
drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Anyone can insert orders" on public.orders;
drop policy if exists "Anyone can insert order items" on public.order_items;
drop policy if exists "Public can read orders" on public.orders;
drop policy if exists "Public can read order items" on public.order_items;
drop policy if exists "Administrators can view and manage all orders" on public.orders;
drop policy if exists "Administrators can view and manage all order items" on public.order_items;
drop policy if exists "Administrators can update orders" on public.orders;
drop policy if exists "Administrators can delete orders" on public.orders;
drop policy if exists "Administrators can update order items" on public.order_items;
drop policy if exists "Administrators can delete order items" on public.order_items;

-- 4. Otorgar permisos SELECT e INSERT tanto a anon como a authenticated
grant select, insert on public.orders to anon, authenticated;
grant select, insert on public.order_items to anon, authenticated;
grant update, delete on public.orders to authenticated;
grant update, delete on public.order_items to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;
grant usage, select on sequence public.order_items_id_seq to anon, authenticated;

-- 5. Crear políticas RLS
-- Permitir creación y lectura para retorno de ID y actualización en vivo
create policy "Anyone can insert orders" on public.orders
  for insert to anon, authenticated with check (true);

create policy "Anyone can insert order items" on public.order_items
  for insert to anon, authenticated with check (true);

create policy "Public can read orders" on public.orders
  for select to anon, authenticated using (true);

create policy "Public can read order items" on public.order_items
  for select to anon, authenticated using (true);

-- Solo administradores pueden modificar o eliminar pedidos
create policy "Administrators can update orders" on public.orders
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Administrators can delete orders" on public.orders
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Administrators can update order items" on public.order_items
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Administrators can delete order items" on public.order_items
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

-- 6. Habilitar Realtime para el panel de administración
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- 7. Índices de rendimiento
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
