-- Ejecuta este archivo una sola vez en Supabase: SQL Editor > New query > Run.
create table if not exists public.production_inventory_items (
  id bigint generated by default as identity primary key,
  world text not null check (world in ('pizza','waffle')),
  name text not null check (char_length(name) between 1 and 80),
  unit text not null default 'unidades' check (char_length(unit) between 1 and 20),
  target numeric not null default 0 check (target >= 0),
  stock numeric not null default 0 check (stock >= 0),
  position integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (world,name)
);
alter table public.production_inventory_items enable row level security;
revoke all on public.production_inventory_items from anon, authenticated;
grant select, insert, update, delete on public.production_inventory_items to authenticated;
grant usage, select on sequence public.production_inventory_items_id_seq to authenticated;
create policy "Administrators manage production inventory" on public.production_inventory_items for all to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid())) with check (exists (select 1 from public.admin_users where user_id = auth.uid()));
insert into public.production_inventory_items (world,name,unit,position) values
  ('pizza','Masa de pizza','unidades',1),('pizza','Pomodoro','kg',2),('pizza','Mozzarella','kg',3),('pizza','Albahaca fresca','paquetes',4),('pizza','Aceite de Oliva','ml',5),('pizza','Jamón pierna','kg',6),('pizza','Champiñones','kg',7),('pizza','Tomate fresco','kg',8),('pizza','Aceitunas negras','kg',9),('pizza','Orégano','g',10),('pizza','Pepperoni','unidades',11),('pizza','Fondo de alcachofa','unidades',12),('pizza','Longaniza artesanal','kg',13),('pizza','Cebolla','kg',14),('pizza','Salsa pesto','ml',15),('pizza','Salsa BBQ','ml',16),('pizza','Tocino','kg',17),
  ('waffle','Masa de waffle','unidades',1),('waffle','Manjar artesanal','kg',2),('waffle','Salsa de chocolate semiamargo','ml',3),('waffle','Chispas de chocolate','g',4)
on conflict (world,name) do nothing;
